name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Create 404 fallback
        run: |
          # Encontra automaticamente a pasta exata onde o index.html foi gerado
          BUILD_DIR=$(dirname $(find . -name "index.html" -not -path "./node_modules/*" -not -path "./src/*" | head -n 1))
          echo "Encontrado em: $BUILD_DIR"
          echo "DIRECTORY_PATH=$BUILD_DIR" >> $GITHUB_ENV
          cp "$BUILD_DIR/index.html" "$BUILD_DIR/404.html"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DIRECTORY_PATH }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
